# SPEC file for gandi-hosting-vm3
# Source file is generated by make tarball-for-rpm in the gandi-hosting-vm3
# svn default repository svn/infra/hosting/gandi-hosting-vm3

%define name    gandi-hosting-vm3
%define version 3.0
%define release 1
%define sourcedir    %{_topdir}/BUILD/%{name}-%{version}

Name:           %{name} 
Summary:        Script for GANDI hosting virtual machine.
Version:        %{version} 
Release:        %{release} 
Source0:        %{name}-%{version}.tar.bz2
URL:            http://www.gandi.net/hosting/ 
License:        Gandi License
BuildArch:      noarch
Group:          System/Configuration 
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-buildroot 
Requires:       openssl, udev, acpid, sed
Provides:       gandi-hosting-vm, gandi-hosting-agent
Obsoletes:      gandi-hosting-vm <= 2.9 , gandi-hosting-agent <= 1.1

%description
Collection of script to handle dynamic resources of virtual
machine on Gandi IaaS hosting solution. most configuration
is done during the first and subsequent boot.

In case of GPT partition on disk, you should install gdisk to
handle the partitions.

%prep 
%setup -q

%install
# $(SRCDIR) by %{sourcedir}
# $(DESTDIR) by $RPM_BUILD_ROOT

# only cp and mkdir here; script and link are done in the %post section
rm -rf $RPM_BUILD_ROOT
install -d -m 0755 $RPM_BUILD_ROOT/etc/gandi
cp -raf %{sourcedir}/etc/gandi	$RPM_BUILD_ROOT/etc/

install -d -m 0755 $RPM_BUILD_ROOT/etc/udev/rules.d
cp -raf %{sourcedir}/etc/udev/rules.d/	$RPM_BUILD_ROOT/etc/udev/

install -d -m 0755 $RPM_BUILD_ROOT/etc/pki/rpm-gpg
install -m 0644 %{sourcedir}/etc/pki/rpm-gpg/RPM-GPG-KEY-Gandi \
	$RPM_BUILD_ROOT/etc/pki/rpm-gpg/

install -d -m 0755 $RPM_BUILD_ROOT/usr/lib/sysctl.d/
install -m 0644 %{sourcedir}/usr/lib/sysctl.d/90-gandi.conf \
	$RPM_BUILD_ROOT/usr/lib/sysctl.d/90-gandi.conf

install -d -m 0755 $RPM_BUILD_ROOT/lib/udev/
install -m 0755 %{sourcedir}/lib/udev/cpu_online	$RPM_BUILD_ROOT/lib/udev/
install -m 0755 %{sourcedir}/lib/udev/fake_blkid	$RPM_BUILD_ROOT/lib/udev/

#mkdir -p $RPM_BUILD_ROOT/etc/auto.master.d
#cp -af %{sourcedir}/etc/auto.master.d/gandi.autofs $RPM_BUILD_ROOT/etc/auto.master.d/
#cp -af %{sourcedir}/etc/auto.gandi $RPM_BUILD_ROOT/etc


%posttrans
sed -i -e 's,^gpgcheck=0,gpgcheck=1\ngpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-Gandi,g' /etc/yum.repos.d/Gandi-Base.repo

# remove old and obsolete plugins
rm -f /etc/gandi/plugins.d/04-config_network
rm -f /etc/gandi/plugins.d/06-vm-fix-cron
rm -f /etc/gandi/plugins.d/05-vm-fix-ext3
rm -f /etc/gandi/plugins.d/07-vm-fix-gandikey
rm -f /etc/gandi/plugins.d/07-timezone
rm -f /etc/gandi/plugins.d/09-config_timezone

# obsolete plugin in 1.2 version
rm -f /etc/gandi/plugins.d/04-config_local_network
rm -f /etc/gandi/plugins.d/05-config_hostname
rm -f /etc/gandi/plugins.d/06-config_nameserver
rm -f /etc/gandi/plugins.d/08-config_user_group
rm -f /etc/gandi/plugins.d/12-vm-fix-umask
rm -f /etc/gandi/plugins.d/15-misc
rm -f /etc/gandi/dhclient-exit-hooks
rm -f /etc/gandi/dhcp-postconf
rm -f /etc/gandi/dhcp-hostname
rm -f /etc/gandi/dhcp-hostname-static-net
rm -rf /etc/gandi/bootstrap.d

# obsolete plugins in gandi-hosting-vm2 version
rm -rf /etc/gandi/plugins.d/00-config_swap
rm -rf /etc/gandi/plugins.d/10-config_sysctl

#
# --- End of %posttrans ---
#


%clean 
rm -rf $RPM_BUILD_ROOT 


%files 
%doc changelog.gz
%defattr(0755,root,root) 
/etc/gandi/manage_data_disk.py
/etc/gandi/manage_iface.sh
/lib/udev/cpu_online
/lib/udev/fake_blkid
#/etc/auto.gandi
%config /etc/udev/rules.d/86-gandi.rules
#%config /lib/udev/rules.d/gandi.rules
/etc/pki/rpm-gpg/RPM-GPG-KEY-Gandi
/etc/gandi/sysctl.conf
/usr/lib/sysctl.d/90-gandi.conf

%changelog 
* Fri Sep 19 2008 Nicolas Chipaux <aegiap@gandi.net> 1.0.0-1474-1gnd
- Bug fixing for packaging and scripts
