#!/bin/sh
# postrm script for gandi-hosting-vm2

set -e

case "$1" in
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        update-rc.d -f gandi-mount remove | \
            grep "Removing any system startup" > /dev/null || true
        update-rc.d -f gandi-config remove | \
            grep "Removing any system startup" > /dev/null || true
        update-rc.d -f gandi-postboot remove | \
            grep "Removing any system startup" > /dev/null || true
        update-rc.d -f gandi-bootstrap remove | \
            grep "Removing any system startup" > /dev/null || true
        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1

esac

exit 0
