#!/bin/sh
# prerm script for gandi-hosting-vm2

set -e

case "$1" in
	remove|deconfigure)
		for elt in config mount postboot bootstrap; do
			systemctl disable gandi-${elt}.service
		done
		;;
	failed-upgrade|upgrade)
		;;
	*)
		echo "prerm called with unknown argument \`$1'" >&2
		exit 1
	;;
esac

#DEBHELPER#

exit 0
