#!/bin/sh
# prerm script for gandi-hosting-vm2

set -e

case "$1" in
    remove|deconfigure)
        # removing services
        if [ -d /etc/systemd/system/multi-user.target.wants ]; then
		syswant=/etc/systemd/system/multi-user.target.wants
        else
		syswant=/etc/systemd/system/default.target.wants
        fi
        for elt in config mount postboot bootstrap; do
            if [ -d /etc/systemd ] && \
               [ -L "$syswant/gandi-$elt" ]; then
                rm -f "$syswant/gandi-$elt.service"
            fi
        done
        ;;
    failed-upgrade|upgrade)
        ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
